---
# tasks file for ansible-roles-microsoft-iis
- name: Install IIS (Web-Server and Web-Common-Http)
  import_tasks: install_iis.yml
  when: ansible_os_family == 'windows' and action == 'install'
  notify: restart_iis

- name: Remove IIS (Web-Server and Web-Common-Http)
  import_tasks: remove_iis.yml
  when: ansible_os_family == 'windows' and action == 'remove'

- name: restart_iis
  notify: restart_iis
  when: ansible_os_family == 'windows' and action == 'restart'